modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="thaumcraft"
    mandatory=true
    versionRange="[${thaumcraft_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="gtceu"
    mandatory=true
    versionRange="[${gtceu_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="[5.14.1,6)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.10,4)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=true
    versionRange="[15.59.0.212,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    mandatory=false
    versionRange="[2001.6.5,)"
    ordering="AFTER"
    side="BOTH"
