#!/usr/bin/env python3
"""Generates the big magic-multiblock pattern classes from the 1.12 sources.

The upstream DeclarativePatternBuilder uses the same `.aisle(String...)` shape
as modern FactoryBlockPattern, so the aisle blocks can be transplanted
verbatim; only the predicate lines are hand-written per machine (kept in this
script so the huge aisle lists never need manual transcription).
"""

from __future__ import annotations

from pathlib import Path

UPSTREAM = Path(r"H:\MinecraftMods\Pollution\src\main\java\meowmel\pollution\common\metatileentity\multiblock")
OUTPUT = Path(r"H:\MinecraftMods\Pollution-Unofficial-1.20.1\src\main\java\meowmel\pollution\common\machine\multiblock\node")

HEADER = """package meowmel.pollution.common.machine.multiblock.node;

import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.BlockPattern;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GTBlocks;
import com.gregtechceu.gtceu.common.data.GTMaterials;
import meowmel.pollution.common.block.PollutionMagicBlocks;
import meowmel.pollution.common.machine.multiblock.MagicStructureElements;

/** Generated by tools/gen_node_patterns.py - do not edit by hand. */
final class {name} {{

    static BlockPattern create(MultiblockMachineDefinition definition) {{
        return FactoryBlockPattern.start({directions})
{aisles}
{predicates}
                .build();
    }}

    private {name}() {{}}
}}
"""

MAGIC_OUTPUT = Path(r"H:\MinecraftMods\Pollution-Unofficial-1.20.1\src\main\java\meowmel\pollution\common\machine\multiblock\magic")

MACHINES = {
    "MetaTileEntityNodeBlastFurnace.java": (
        "NodeBlastFurnacePatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('A', Predicates.blocks(PollutionMagicBlocks.TUNGSTENSTEEL_GEARBOX.get()))
                .where('B', Predicates.blocks(PollutionMagicBlocks.MANA_BASIC.get())
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1))
                        .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(3))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1))
                        .setMinGlobalLimited(20))
                .where('C', MagicStructureElements.frame(GTMaterials.HSSG))
                .where('D', Predicates.blocks(PollutionMagicBlocks.VOID_PRISM.get()))
                .where('E', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_4.get()))
                .where('F', Predicates.blocks(PollutionMagicBlocks.TUNGSTENSTEEL_PIPE.get()))
                .where('G', Predicates.blocks(PollutionMagicBlocks.AAMINATED_GLASS.get()))
                .where('H', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_0.get()))
                .where('I', Predicates.heatingCoils())
                .where('X', Predicates.blocks(PollutionMagicBlocks.MANA_BASIC.get()))
                .where('Y', Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1))""",
    ),
    "MetaTileEntityNodeFusionReactor.java": (
        "NodeFusionReactorPatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('A', Predicates.blocks(GTBlocks.FUSION_GLASS.get()))
                .where('B', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_1.get()))
                .where('D', Predicates.blocks(PollutionMagicBlocks.VOID_PRISM.get())
                        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(16))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))
                .where('E', Predicates.blocks(GTBlocks.SUPERCONDUCTING_COIL.get()))
                .where('F', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_VOID.get())
                        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(5)))
                .where('G', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_VOID.get())
                        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1)))
                .where('H', Predicates.abilities(PartAbility.IMPORT_ITEMS).setExactLimit(1))""",
    ),
    "MetaTileEntityEssenceCollector.java": (
        "EssenceCollectorPatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('A', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM.get())
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1))
                        .setMinGlobalLimited(200))
                .where('B', Predicates.heatingCoils())
                .where('C', Predicates.blocks(PollutionMagicBlocks.LAMINATED_GLASS.get()))
                .where('D', Predicates.abilities(PartAbility.EXPORT_FLUIDS).setExactLimit(6))
                .where('E', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_4.get()))
                .where('F', Predicates.blocks(PollutionMagicBlocks.STAINLESS_STEEL_GEARBOX.get()))
                .where('G', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_VOID.get()))
                .where('H', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_EARTH.get()))
                .where('I', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_WATER.get()))
                .where('J', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_HOT.get()))
                .where('K', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_AIR.get()))
                .where('L', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_ORDER.get()))
                .where('O', Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2))""",
    ),
    "MetaTileEntityMagicFusionReactor.java": (
        "MagicFusionReactorPatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('A', MagicStructureElements.frame(GTMaterials.TungstenSteel)
                        .setMinGlobalLimited(105)
                        .or(Predicates.autoAbilities(meowmel.pollution.api.recipes.PORecipeMaps.MAGIC_FUSION_REACTOR)))
                .where('B', Predicates.heatingCoils())
                .where('C', Predicates.blocks(PollutionMagicBlocks.VOID_PRISM.get()))
                .where('D', Predicates.blocks(PollutionMagicBlocks.BAMINATED_GLASS.get()))""",
    ),
    "MetaTileEntityMagicBattery.java": (
        "MagicBatteryPatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('A', Predicates.blocks(PollutionMagicBlocks.MAGIC_BATTERY_CASING.get())
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(16))
                        .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setMaxGlobalLimited(16))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))
                .where('B', MagicStructureElements.batteryCores())
                .where('C', MagicStructureElements.batteryCoils())""",
    ),
    "MetaTileEntityIndustrialInfusion.java": (
        "IndustrialInfusionPatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('B', Predicates.blocks(PollutionMagicBlocks.SPELL_PRISM_VOID.get())
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(16))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))
                .where('C', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_4.get()))
                .where('D', Predicates.blocks(PollutionMagicBlocks.TITANIUM_PIPE.get()))
                .where('E', Predicates.blocks(PollutionMagicBlocks.TITANIUM_GEARBOX.get()))
                .where('F', Predicates.blocks(PollutionMagicBlocks.MAGIC_BATTERY_CASING.get()))""",
    ),
    "MetaTileEntityCentralVisTower.java": (
        "CentralVisTowerPatterns",
        """                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                .where('A', Predicates.blocks(PollutionMagicBlocks.MANA_BASIC.get()))
                .where('B', frameGroup())
                .where('C', MagicStructureElements.frame(GTMaterials.NaquadahAlloy))
                .where('D', Predicates.blocks(GTBlocks.FUSION_GLASS.get()))
                .where('E', Predicates.blocks(PollutionMagicBlocks.MANA_2.get()))
                .where('F', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_1.get()))
                .where('G', Predicates.blocks(PollutionMagicBlocks.MANA_1.get()))
                .where('H', Predicates.blocks(PollutionMagicBlocks.LAMINATED_GLASS.get()))
                .where('J', Predicates.blocks(PollutionMagicBlocks.BEAM_CORE_4.get()))
                .where('K', Predicates.blocks(PollutionMagicBlocks.MANA_BASIC.get())
                        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS)
                                .setMinGlobalLimited(3).setMaxGlobalLimited(8))
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1)))""",
    ),
}

FRAME_GROUP = """
    private static com.gregtechceu.gtceu.api.pattern.TraceabilityPredicate frameGroup() {
        return MagicStructureElements.frame(GTMaterials.HSSG)
                .or(MagicStructureElements.frame(GTMaterials.NaquadahAlloy))
                .or(MagicStructureElements.frame(GTMaterials.TungstenSteel))
                .or(MagicStructureElements.frame(GTMaterials.StainlessSteel));
    }
"""


def strip_block_comments(text: str) -> str:
    """Removes /* ... */ blocks so commented-out legacy patterns are ignored."""
    import re

    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def extract_aisles(path: Path) -> list[str]:
    aisles: list[str] = []
    buffer = ""
    text = strip_block_comments(path.read_text(encoding="utf-8", errors="replace"))
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("//"):
            continue
        if not buffer:
            if stripped.startswith(".aisle("):
                buffer = stripped
        else:
            buffer += " " + stripped
        if buffer and buffer.rstrip().endswith(")"):
            aisles.append("                " + buffer.rstrip())
            buffer = ""
    return aisles


def main() -> int:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for source_name, (class_name, predicates) in MACHINES.items():
        aisles = extract_aisles(UPSTREAM / source_name)
        if not aisles:
            print(f"!! no aisles found for {source_name}")
            continue
        content = HEADER.format(directions="com.gregtechceu.gtceu.api.pattern.util.RelativeDirection.RIGHT, com.gregtechceu.gtceu.api.pattern.util.RelativeDirection.UP, com.gregtechceu.gtceu.api.pattern.util.RelativeDirection.FRONT" if class_name == "MagicBatteryPatterns" else "", name=class_name, aisles="\n".join(aisles), predicates=predicates)
        if "frameGroup" in predicates:
            content = content.replace(f"    private {class_name}() {{}}",
                                      FRAME_GROUP + f"\n    private {class_name}() {{}}")
        magic_classes = ("EssenceCollectorPatterns", "IndustrialInfusionPatterns",
                         "MagicFusionReactorPatterns", "MagicBatteryPatterns")
        target_dir = MAGIC_OUTPUT if class_name in magic_classes else OUTPUT
        package_line = ("package meowmel.pollution.common.machine.multiblock.node;"
                        if class_name not in magic_classes
                        else "package meowmel.pollution.common.machine.multiblock.magic;")
        content = content.replace("package meowmel.pollution.common.machine.multiblock.node;", package_line, 1)
        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / f"{class_name}.java").write_text(content, encoding="utf-8")
        print(f"wrote {class_name}.java ({len(aisles)} aisles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
