package meowmel.pollution.common.machine.multiblock.magic;

import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.BlockPattern;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.recipe.GTRecipeType;
import com.gregtechceu.gtceu.common.data.GTBlocks;
import com.gregtechceu.gtceu.common.data.GTMaterials;
import meowmel.pollution.api.metatileentity.POMultiblockAbility;
import meowmel.pollution.common.block.PollutionMagicBlocks;
import meowmel.pollution.common.machine.multiblock.MagicStructureElements;

/** Generated by tools/gen_node_patterns.py - do not edit by hand. */
final class MagicFusionReactorPatterns {

    static BlockPattern create(MultiblockMachineDefinition definition) {
        return FactoryBlockPattern.start()
                .aisle("           ", "           ", "           ", "     A     ", "     A     ", "   AAAAA   ", "     A     ", "     A     ", "           ", "           ", "           ")
                .aisle("           ", "     A     ", "     A     ", "   BBABB   ", "   B   B   ", "  AA A AA  ", "   B   B   ", "   BBABB   ", "     A     ", "     A     ", "           ")
                .aisle("           ", "     A     ", "           ", "           ", "    CCC    ", " A  CCC  A ", "    CCC    ", "           ", "           ", "     A     ", "           ")
                .aisle("     A     ", "   BBABB   ", "           ", " B       B ", " B  DDD  B ", "AA  DDD  AA", " B  DDD  B ", " B       B ", "           ", "   BBABB   ", "     A     ")
                .aisle("     A     ", "   B   B   ", "    CCC    ", " B  DDD  B ", "  CD   DC  ", "A CD   DC A", "  CD   DC  ", " B  DDD  B ", "    CCC    ", "   B   B   ", "     A     ")
                .aisle("   AAAAA   ", " AAA A AAA ", " A  CCC  A ", "AA  DDD  AA", "A CD   DC A", "AACD   DCAA", "A CD   DC A", "AA  DDD  AA", " A  CCC  A ", " AAA A AAA ", "   AAAAA   ")
                .aisle("     A     ", "   B   B   ", "    CCC    ", " B  DDD  B ", "  CD   DC  ", "A CD   DC A", "  CD   DC  ", " B  DDD  B ", "    CCC    ", "   B   B   ", "     A     ")
                .aisle("     A     ", "   BBABB   ", "           ", " B       B ", " B  DDD  B ", "AA  DDD  AA", " B  DDD  B ", " B       B ", "           ", "   BBABB   ", "     A     ")
                .aisle("           ", "     A     ", "           ", "           ", "    CCC    ", " A  CCC  A ", "    CCC    ", "           ", "           ", "     A     ", "           ")
                .aisle("           ", "     A     ", "     A     ", "   BBABB   ", "   B   B   ", "  AA A AA  ", "   B   B   ", "   BBABB   ", "     A     ", "     A     ", "           ")
                .aisle("           ", "           ", "           ", "     A     ", "     A     ", "   AASAA   ", "     A     ", "     A     ", "           ", "           ", "           ")
                .where('S', Predicates.controller(Predicates.blocks(definition.get())))
                .where(' ', Predicates.any())
                // 上游该机外壳不含 MANA_INPUT_HATCH，能源仓也没有数量下限
                .where('A', MagicStructureElements.frame(GTMaterials.TungstenSteel)
                        .or(Predicates.autoAbilities(
                                new GTRecipeType[]{meowmel.pollution.api.recipes.PORecipeMaps.MAGIC_FUSION_REACTOR},
                                false, false, true, true, true, true))
                        .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                        .or(Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1))
                        .or(Predicates.abilities(POMultiblockAbility.VIS_HATCH).setMaxGlobalLimited(1))
                        .or(Predicates.abilities(POMultiblockAbility.INFUSED_FLUID_HATCH).setExactLimit(1))
                        .or(Predicates.abilities(POMultiblockAbility.MANA_INPUT_POOL).setMaxGlobalLimited(1))
                        .or(Predicates.abilities(POMultiblockAbility.TAROT_HATCH).setMaxGlobalLimited(1)))
                .where('B', Predicates.heatingCoils())
                .where('C', Predicates.blocks(PollutionMagicBlocks.VOID_PRISM.get()))
                .where('D', Predicates.blocks(PollutionMagicBlocks.BAMINATED_GLASS.get()))
                .build();
    }

    private MagicFusionReactorPatterns() {}
}
