package meowmel.pollution.gametest;

import com.gregtechceu.gtceu.api.registry.GTRegistries;
import meowmel.pollution.Pollution;
import meowmel.pollution.api.pollution.PollutionEngine;
import meowmel.pollution.common.item.PackagedAuraNode;
import meowmel.pollution.common.item.PollutionItems;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.gametest.GameTestHolder;

/**
 * GameTests of the Pollution port.
 *
 * <p>Run with the ForgeGradle task {@code runGameTestServer}. The shared
 * template is a flat 3x3 stone platform generated by
 * {@code tools/gen_gametest_structure.py}.</p>
 */
@GameTestHolder(Pollution.MOD_ID)
public final class PollutionGameTests {

    private static final String[] MAGIC_MACHINES = {
            "magic_macerator", "magic_bender", "magic_centrifuge", "magic_electrolyzer",
            "magic_electric_blast_furnace", "magic_alloy_blast", "magic_chemical_reactor",
            "magic_assembler", "node_producer", "large_node_generator", "node_washer",
            "node_blast_furnace", "luv_node_fusion_reactor", "central_vis_tower",
            "essence_smelter", "gt_essence_smelter", "essence_collector", "industrial_infusion",
    };

    private PollutionGameTests() {}

    @GameTest(template = "pollution:platform", batch = "pollution")
    public static void pollutionEngineRoundTrip(GameTestHelper helper) {
        ServerLevel level = helper.getLevel();
        BlockPos pos = helper.absolutePos(new BlockPos(1, 2, 1));

        PollutionEngine.set(level, pos, 0);
        PollutionEngine.add(level, pos, 4.5);
        if (Math.abs(PollutionEngine.get(level, pos) - 4.5) > 1.0E-6) {
            helper.fail("pollution add/get mismatch: " + PollutionEngine.get(level, pos));
        }
        PollutionEngine.scrub(level, pos, 2.0);
        if (Math.abs(PollutionEngine.get(level, pos) - 2.5) > 1.0E-6) {
            helper.fail("pollution scrub mismatch: " + PollutionEngine.get(level, pos));
        }
        PollutionEngine.set(level, pos, 0);
        helper.succeed();
    }

    @GameTest(template = "pollution:platform", batch = "pollution")
    public static void magicMachinesRegistered(GameTestHelper helper) {
        for (String path : MAGIC_MACHINES) {
            ResourceLocation id = ResourceLocation.fromNamespaceAndPath(Pollution.MOD_ID, path);
            if (GTRegistries.MACHINES.get(id) == null) {
                helper.fail("missing machine definition: " + id);
            }
        }
        helper.succeed();
    }

    @GameTest(template = "pollution:platform", batch = "pollution")
    public static void packagedNodeNbtRoundTrip(GameTestHelper helper) {
        ItemStack stack = new ItemStack(PollutionItems.PACKAGED_AURA_NODE.get());
        stack.getOrCreateTag().putString(PackagedAuraNode.TAG_TIER, "Bright");
        stack.getOrCreateTag().putString(PackagedAuraNode.TAG_TYPE, "Pure");
        PackagedAuraNode.setEssence(stack, PackagedAuraNode.ESSENCE_FIRE, 250);

        if (!"Bright".equals(PackagedAuraNode.tier(stack))) {
            helper.fail("node tier did not round trip");
        }
        if (!"Pure".equals(PackagedAuraNode.type(stack))) {
            helper.fail("node type did not round trip");
        }
        if (PackagedAuraNode.essence(stack, PackagedAuraNode.ESSENCE_FIRE) != 250) {
            helper.fail("node essence did not round trip");
        }
        helper.succeed();
    }

    @GameTest(template = "pollution:platform", batch = "pollution")
    public static void magicCasingsRegistered(GameTestHelper helper) {
        for (String path : new String[]{"spell_prism_earth", "spell_prism_void", "beam_core_4",
                "baminated_glass", "magic_battery_casing", "polytetrafluoroethylene_pipe"}) {
            ResourceLocation id = ResourceLocation.fromNamespaceAndPath(Pollution.MOD_ID, path);
            if (!net.minecraft.core.registries.BuiltInRegistries.BLOCK.containsKey(id)) {
                helper.fail("missing casing block: " + id);
            }
        }
        helper.succeed();
    }
}
